### ISSUE TITLE
關於 api 的樣子的討論～

### ISSUE THREAD

**Issue by chhsiao1981** [Ptt-official-app/go-openbbsmiddleware#18]
目前 api reference 如 

http://173.255.216.176:5000/

ASKA LEE 提出以下 api 樣子:

|method    | path                    | query
|----------|-----------------|-----------------------------------------
| GET         |/api/Articals        | ?isPopular=title=beforeTime=desc=
| GET         |/api/Articals/{id} |
| PUT        |/api/Articals/{id}  |
| DELETE  | /api/Articals/{id}
| GET         |/api/Boards         |?isPopular=title=beforeTime=desc=
| GET         |/api/Boards/{id} |
| PUT         |/api/Boards/{id} |
| DELETE  | /api/Boards/{id} |
| GET        | /api/Boards/{id}/Articles|?isPopular=title=beforeTime=desc=
| GET        | /api/Boards/{id}/Articles/{id}|
| GET       | /api/Boards/{id}/Users|?name=desc=
| GET       | /api/Boards/{id}/Users/{id}|
| GET       | /api/Users|?isVisible=desc=
| GET       | /api/Users/{id}|
| PUT       | /api/Users/{id}|
| DELETE | /api/Users/{id}|
|GET        | /api/Users/{id}/Comments|?desc=
|GET        |/api/Users/{id}/Favorites|?title=
|GET        |/api/Users/{id}/Articals|?title=desc=

**Comment by chhsiao1981** [comment]
1. Articles 拼錯字為 Articals
2. 目前已有 /api/boards/popular 和 /api/board/{id} 的分別. 而可以容易直接呈現在 swagger 的畫面上讓 frontend 容易知道熱門看板如何取得. 將單一 object 和 list 分開應該是比較好的 setup～
3. 目前 list 類的 query 已經有 max=, 可改成大家常聽到的 limit=, 目前的 keyword= 可以改成 tilte= 和 name=
4. 可在目前 list 類的 query 加上 desc=
5. 會增加板友名單類 api.
6. 不建議使用 PUT / DELETE. 會是在 POST 裡加上 ?action=

**Comment by tracyxxlee** [comment]
2. 建議使用 /api/board/{id}?isPopular=true 替代 /api/boards/popular，前後端只需維護一個 API
4. 同意加上 desc，一般以發文時間排序，沒有發文時間者，例如看板，要以甚麼排序?
6. 需要訂定 action 名稱，例如Delete -> action=delete，PUT=?

**Comment by chhsiao1981** [comment]
@tracyxxlee 

2. 在現在需要快速 dev 階段. 重點在於如何讓 frontend-developer 可以在 http://173.255.216.176:5000/ 第一眼就知道 api 要怎樣子用～
    有提到說並不希望像 https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html 如此的 parameter 災難.
    你可以: 1. git clone 這個 repo. 2. 開個 branch 修改 apidoc 下的 API-definition. 3. PR
    我們可以根據 swagger 呈現的方式來比較如何讓 frontend-developer

3. 根據目前 ptt 運行方式. 看板有兩種排序方式. 1. by brdname. 2. by class, by brdname..
4. Delete => action=delete,PUT => action=put

**Comment by chhsiao1981** [comment]
The official api in swagger-ui can be found in https://api.devptt.site:5000.

It's with CORS capability and the api can be tested directly from the site.
