### ISSUE TITLE
文章裡的 url 使用新版的 url

### ISSUE THREAD

**Issue by chhsiao1981** [Ptt-official-app/go-openbbsmiddleware#220]
# Provide the github link(s) of the file#line (請提供 github 關於 code 的 link)

https://github.com/Ptt-official-app/go-openbbsmiddleware/blob/6111013d5d003f943a011c6b1f2173c84c7c5ff9/apitypes/utils.go#L9

# What would you like to discuss (你想要討論什麼呢？～)

目前是比照 c-pttbbs 變成 www.ptt.cc/bbs 的 URL～
需要改成這個版本的 URL

/board/{board_id}/article/{article_id}

**Comment by chhsiao1981** [comment]
可以考慮以下 url convention:

GET:
/bbs/hotboards.html => 熱門文章
/bbs/{board_id} => show 文章 list
/bbs/{board_id}/{article_id}.html => show 文章
/cls/{cls_id} => show 分類看板
/user/{user_id}/favorites => 我的最愛
/user/{user_id} => user 的歷史文章 / comments
/user/{user_id}/about => user info

POST:
/bbs/{board_id} => 發文
/bbs/{board_id}/article_id}.html => 推噓
/cls/{cls_id}/create => 新增看板
/cls/{cls_id}/createcls => 新增 class
/user/{user_id}/favorites => 新增我的最愛

**Comment by tingyuchang** [comment]
我來試看看這個 issue 吧，不過有個問題是 AllPOST 的 url 應該還是要指向 original board ，ptt 原本的做法應該是讀取文章的 file ，所以不會有這個問題，今天要從 bid, aid 轉換成 url 的時候，應該要做轉換才對？

btw 請問上面 url conversion 的意思是？不太明白跟這個 issue 關係，謝謝

**Comment by chhsiao1981** [comment]
hi @tingyuchang～

非常感謝願意幫忙～

ToURL 這個 function 是在

https://github.com/Ptt-official-app/go-openbbsmiddleware/blob/main/apitypes/article_summary.go#L38

這裡用到～
傳給 frontend 讓他們如果有需要做 redirect to web-url 時可以使用～

目前新版 url 的格式是

types.URL_PREFIX + "/board/" + string(fbboardID) + "/article/" + string(farticleID)

ex: 
https://www.devptt.site/board/Baseball/article/M.1619324039.A.632

沒有意外的話～ 應該就會是如此新版的格式～




上面的討論是在考慮是否要參考/延伸目前 ptt web 版 (https://www.ptt.cc/bbs) 的格式～

由於 golang 目前有一些 routing 的限制～
所以參考/延伸目前 ptt web 版 (https://www.ptt.cc/bbs) 可能會有困難～
目前先不考慮這部分～

**Comment by tingyuchang** [comment]
好的，如果不考慮 ALLPOST 的特殊性，改從 mongodb 直接出資料那應該就沒問題了，今天應該就可以發 PR

**Comment by chhsiao1981** [comment]
#310 resolves this issue.
