### ISSUE TITLE
註冊 / login 會同步更改上站次數/上站時間.

### ISSUE THREAD

**Issue by chhsiao1981** [Ptt-official-app/go-openbbsmiddleware#248]
**Is your feature request related to a problem? Please describe.**

https://github.com/Ptt-official-app/go-pttbbs/blob/main/ptt/mbbsd.go#L81

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tingyuchang** [comment]
go-pttbbs 的開發環境已經跑起來

**Comment by tingyuchang** [comment]
go-pttbbs 的開發環境已經跑起來

這個需求應該是要改 NumLoginDays 跟 LastLogin? 不過我對 shm 不太熟，我先研究一下的寫法 

NumLoginDays 應該有每天最多+1的限制，不知道是否還有其他規則呢？

**Comment by chhsiao1981** [comment]
@tingyuchang 

非常感謝～

剛剛在 go-pttbbs 開了相關 issue～

https://github.com/Ptt-official-app/go-pttbbs/issues/250

把 pwcuLoginSave implement 完應該就差不多了～

**Comment by tingyuchang** [comment]
pwcuLoginSave 是原本的 c-ptt sourcecode 嗎？請問要去哪邊看呢？

**Comment by chhsiao1981** [comment]
@tingyuchang 

pwcuLoginSave:

https://github.com/ptt/pttbbs/blob/master/mbbsd/passwd.c#L501

**Comment by tingyuchang** [comment]
對 C 沒有很熟，看完感覺是從 lastlogin 來判斷，是否要 +1 ，還有處理每天最多 +1 的邏輯，另外這邊也需要更新以下的兩個參數
`user.LastLogin = types.NowTS()`
`user.LastSeen = types.NowTS()`

btw logins.bad & logins.recent 似乎也沒有寫入？

**Comment by chhsiao1981** [comment]
https://github.com/Ptt-official-app/go-pttbbs/pull/251 resolves this issue.
