### ISSUE TITLE
關於 user-login 的 log.

### ISSUE THREAD

**Issue by chhsiao1981** [Ptt-official-app/go-openbbsmiddleware#262]
**Is your feature request related to a problem? Please describe.**
關於 user-login 的 log.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by tingyuchang** [comment]
請問這個 issue 具體來說希望能做到什麼程度呢？

**Comment by chhsiao1981** [comment]
@tingyuchang 

目的: 

包含著 {loginID, IP, clientInfo, updateNanoTS, success}, 在

https://github.com/Ptt-official-app/go-openbbsmiddleware/blob/main/api/login.go

裡都會紀錄
(建議在  

https://github.com/Ptt-official-app/go-openbbsmiddleware/blob/main/api/login.go#L48

使用 defer funct() {}() 的方式來確保每個 login 都有被記錄到～)

這個 issue 先使用 logrus.Infof() 印在 stderr 裡好了～


TODO: user-login-history 是直接放到 kafka 裡～

https://github.com/confluentinc/confluent-kafka-go

**Comment by tingyuchang** [comment]
Ok 那我來接這個 issue ，再麻煩 assign 給我，謝謝

**Comment by tingyuchang** [comment]
btw kafka 的機制要一起做嗎？在 login success 之後發送過去。我可以把 kafka 的 service 建立起來，放在 docker compose 裡面

**Comment by chhsiao1981** [comment]
hi @tingyuchang ～

kafka 先不用好了～
預期 kafka 的內容之後有可能會再往後送做更多事情～
我們需要有個類似 schema/ 的方式來記錄 kafka 的內容～

**Comment by tingyuchang** [comment]
![Screen Shot 2021-08-24 at 7 30 04 PM](https://user-images.githubusercontent.com/1683956/130609148-03174c10-8eb0-4c13-837e-765cbe97514b.png)
訊息印出來大概會是這樣

**Comment by chhsiao1981** [comment]
@tingyuchang 

Cool!

可以來一下 PR～

**Comment by chhsiao1981** [comment]
#311 resolves this issue.
