### ISSUE TITLE
複製來的文章，推文時間錯誤（相差一年）

### ISSUE THREAD

**Issue by lydia7635** [Ptt-official-app/go-openbbsmiddleware#349]
**Describe the bug**
devptt 上的 WhoAmI 板裡有一些複製來的測試文章（包含留言），其中標題為 **[討論] 測試色碼 3** 的留言部分時間判斷錯誤

**To Reproduce**
1. curl 傳送 request
  ```
  curl -X 'GET' \
      'https://api.devptt.site:3457/api/board/WhoAmI/article/M.1621089154.A.B39/comments?limit=5&desc=true' \
      -H 'accept: */*'
  ```
或是 request URL: https://api.devptt.site:3457/api/board/WhoAmI/article/M.1621089154.A.B39/comments?limit=5&desc=true
2. 結果 (response body) （太長因此只放一小部分，create_time 有誤）
  ```
  "bid": "WhoAmI",
  "aid": "M.1621089154.A.B39",
  "cid": "FoML5E-iVDA:9fJnW9k0qnOtNnani_mlaw",
  "type": 1,
  "refid": "",
  "deleted": false,
  "create_time": 1651888140,
  "sort_time": 1622153365,
  "owner": "zhibb",
  "content": [
    [
      {
        "text": "謝謝活動部 :)",
        "color0": {
          "foreground": 37,
          "background": 40,
          "blink": false,
          "highlight": false,
          "reset": false
        },
  ```
3. 此篇文章有三個留言，只有最後一個留言的時間 (user: Japan2001) 的時間正確，其它兩個留言的時間比預期多了一年（為 2022 年，實際上應為 2021 年），因此在 devptt 網頁版的排序也錯誤。
![image](https://user-images.githubusercontent.com/44331020/149320812-2dbd3d0f-6936-495d-bcb3-b316a716617f.png)

**Expected behavior**
留言的 create_time 時間正確。

**Additional context**
不確定是不是 go-openbbsmiddleware 的問題，也有可能是 go-pttbbs 儲存到錯誤的時間。

**Comment by chhsiao1981** [comment]
把 article / comment 砍掉重 load 以後還是一樣的結果～
會做 test 確認到底發生什麼事情～.

**Comment by chhsiao1981** [comment]
這篇產生過程是:
1. 按照正常 api 方式 create 1 個空 post. (正常的發文時間)
2. 將 ptt.cc 裡 SYSOP 的原文 (透過"Fw 到外部信箱"這個功能) replace 到這個 post. (不正常的推文時間)

導致如下情形:

發文時間: 1621089154 (05/15/2021 22:32:34 CST)
推文0 (ericf129): 05/06 10:57 (比發文早. 所以把年份往後 + 1 (2022))
推文1 (zhibb): 05/07 09:49 (比推文0 晚. 並且"月/日 時/分"沒有變小. 年份跟推文0 一致 (2022))

推文2 (Japan2001): 05/08 06:57 (要求最後一個推文跟文章 modified 時間一致. 年份跟發文一樣 (2021))

https://github.com/Ptt-official-app/go-openbbsmiddleware/blob/27cc45f5b1fba1122d15faad2d3cef95578811ec/dbcs/edit_distance.go#L442
(年份 + 1)

https://github.com/Ptt-official-app/go-openbbsmiddleware/blob/27cc45f5b1fba1122d15faad2d3cef95578811ec/dbcs/edit_distance.go#L368
(align 最後一個推文)



考慮到有可能會有短暫的時間差.
在 infer 年份時. 會把 start-time (文章 create-time) 往前一段時間 (2 weeks) 和 end-time (文章 modified-time) 往後 1 段時間 (2 weeks)
