### ISSUE TITLE
Releasing restriction in register-client.

### ISSUE THREAD

**Issue by chhsiao1981** [Ptt-official-app/go-openbbsmiddleware#60]
# Provide the github link(s) of the file#line (請提供 github 關於 code 的 link)

https://github.com/Ptt-official-app/go-openbbsmiddleware/blob/main/api/register_client.go#L36

# What would you like to discuss (你想要討論什麼呢？～)

currently register-client is restricted to localhost, causing trouble when developing-with-docker locally.
the restriction should be optional (but should be restricted by default.)

**Comment by solring** [comment]
紀錄一下我這邊用docker run go-openbbsmiddleware+go-pttbbs的使用步驟：
1. 設定```docker_compose.env```裡的shared volume位置，可參考```docker-compose.yaml``` 查看需要設定的volume
2. 在middleware使用的ETC volume放入```production.ini```，可以直接使用repo裡的```01-config.docker.ini```
3. (optional) 將```docker-compose.yaml```裡的mongo volume改成自己設定的位置

使用docker-compose 跑起來之後container們都可以正常運作
但在使用register client的api時會因為```remoteAddr```不是localhost而被擋住
測試用script:
``` sh
curl -i -X POST -d '{"client_id": "test_client_id", "client_secret": "test_client_secret"}' 'localhost:3457/api/client/register
```

**Comment by chhsiao1981** [comment]
#61  resolved this issue.
(skipping remote-addr in dev mode.)
